# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Change your own setup in these files (and overwrite any settings from defaults!)

source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/bindings.conf
# source = ~/.config/hypr/conf/hypridle.conf
# source = ~/.config/hypr/conf/hyprlock.conf
# source = ~/.config/hypr/conf/hyprsunset.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/looknfeel.conf
source = ~/.config/hypr/conf/monitors.conf
# source = ~/.config/hypr/conf/xdph.conf
source = ~/.config/hypr/conf/env.conf


