# ============================================================
# autostart.conf — Songster's autostart
# ============================================================

exec-once = uwsm-app -- waybar
exec-once = uwsm-app -- hyprpaper
exec-once = uwsm-app -- /usr/lib/hyprpolkitagent/hyprpolkitagent
exec-once = uwsm-app -- nm-applet --indicator
exec-once = uwsm-app -- swaync
# Clipboard history (requires wl-clipboard)
exec-once = wl-paste --type text --watch cliphist -max-items 50 store
exec-once = wl-paste --type image --watch cliphist -max-items 10 store
