# ============================================================
# autostart.conf — Songster's autostart
# ============================================================
exec-once = uwsm-app -- waybar
exec-once = uwsm-app -- awww-daemon
exec-once = uwsm-app -- /usr/lib/hyprpolkitagent/hyprpolkitagent
exec-once = uwsm-app -- nm-applet --indicator
exec-once = uwsm-app -- swaync
exec-once = wl-paste --type text --watch cliphist -max-items 50 store
exec-once = wl-paste --type image --watch cliphist -max-items 10 store
exec-once = ~/.config/hypr/scripts/restore-wallpaper.sh
