--ozone-platform=wayland
--enable-features=WaylandWindowDecorations,VaapiVideoDecoder,VaapiIgnoreDriverChecks,VaapiVideoEncoder,CanvasOopRasterization
--use-gl=egl
--enable-gpu-rasterization
--enable-accelerated-video-decode
--enable-accelerated-video-encode
--enable-wayland-ime
--disable-features=TranslateUI
